#!/usr/bin/env python3
import os
import sys
import json
import requests
from google import genai
from google.genai import types
from pydantic import BaseModel, Field

# Configurations from environment
GITHUB_TOKEN = os.getenv("GITHUB_TOKEN")
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY")
REPO = os.getenv("GITHUB_REPOSITORY")
PR_NUMBER = os.getenv("PR_NUMBER")
MODEL_NAME = "gemini-3.1-pro-preview"

if not all([GITHUB_TOKEN, GEMINI_API_KEY, REPO, PR_NUMBER]):
    raise ValueError("Missing required environment variables.")


def get_pr_metadata():
    """Fetches the PR title and description body."""
    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application.vnd.github.v3+json",
    }
    response = requests.get(url, headers=headers)
    response.raise_for_status()
    data = response.json()
    return {"title": data.get("title", ""), "body": data.get("body", "")}


def get_pr_diff():
    response = requests.get(f"https://patch-diff.githubusercontent.com/raw/nyx-space/nyx/pull/{PR_NUMBER}.patch")
    response.raise_for_status()
    return response.text


def post_review_comments(comments):
    if not comments:
        print("No recommendations generated by the model.")
        return

    url = f"https://api.github.com/repos/{REPO}/pulls/{PR_NUMBER}/reviews"
    headers = {
        "Authorization": f"token {GITHUB_TOKEN}",
        "Accept": "application.vnd.github.v3+json",
    }

    # Map the JSON structure to GitHub's Review Comments API format
    github_comments = []
    for c in comments:
        github_comments.append(
            {
                "path": c["path"],
                "line": int(c["line"]),
                "side": "RIGHT",
                "body": f"{c['explanation']}\n\n```suggestion\n{c['suggestion'].strip()}\n```",
            }
        )

    payload = {
        "body": "🤖 Automated Gemini Code Review Strategy execution complete. Details appended inline.",
        "event": "COMMENT",
        "comments": github_comments,
    }

    res = requests.post(url, headers=headers, json=payload)
    res.raise_for_status()
    print(f"Successfully posted {len(github_comments)} review comments.")


# Define standard Pydantic models for structured output
class ReviewComment(BaseModel):
    path: str = Field(
        description="Relative file path from repo root. Must match the exact file header in the diff."
    )
    line: int = Field(
        description="The exact target line number in the NEW version of the file where the modification occurs. Crucial: Must be a line present within the provided diff hunk lines."
    )
    explanation: str = Field(
        description="Concise architectural rationale for the change."
    )
    suggestion: str = Field(
        description="The exact code replacement block. Do not include markdown wrappers here."
    )


class ReviewPayload(BaseModel):
    comments: list[ReviewComment] = Field(description="List of inline code suggestions")


SYSTEM_INSTRUCTION = """
You are a principal systems architect and spaceflight dynamics software engineer conducting a strict pull request review for the Nyx Space ecosystem.
The codebase is written in high-performance Rust.

Nyx is a high fidelity, fast, reliable and validated astrodynamics toolkit library written in Rust and available in Python.
Nyx uses ANISE for all SPICE-related computation, frame transformations, rotation calculations, orbital element calculations, etc.
ANISE is a thread-safe, zero-cost alternative to NASA SPICE toolkit, computing spacecraft, planetary, coordinate frame, instrument transformations, ground station visibility, and orbital elements. Engineered for high-throughput Python concurrent execution and flight software, with proven lunar flight heritage.
All time scale and duration computations are managed through Hifitime.
Hifitime is an overflow-safe, high-performance datetime library providing leap-second-correct nanosecond precision across UTC, GPST, and relativistic time-scales. Flight-proven in lunar and deep-space missions.
New additions to the Nyx code base ought to be tested.

Review the incoming unified diff carefully. Identify architectural flaws, performance bottlenecks, mathematical precision errors, or non-idiomatic Rust patterns.
Sanity check the astrodynamics, pointing out possible errors in the underlying physics. If you find simplifications, comment on when the simplification may become an issue.

Strict Domain Constraints:
1. Memory Allocations: Flags allocations (e.g., Vec, Box, clones) inside tight evaluation loops or numerical propagation engines. Favor zero-cost abstractions.
2. Chronometry & Frames: Ensure correct time scale usage via hifitime. Watch out for naive handling of relativistic time updates, epoch arithmetic, or reference frame transforms via ANISE.
3. Actionable Suggestions: For every critique, attempt provide a precise code replacement block that fixes the issue exactly. Ensure your suggestion aligns perfectly with the target line context.

You must output valid JSON matching the schema precisely. Do not hallucinate line numbers. If a file requires no changes, omit it from the array.
You will be evaluated based on the absolute structural accuracy of your line targets.

CRITICAL LINE-NUMBER DIRECTIVE:
- For every review comment you generate, the `line` property MUST correspond strictly to a valid line number added or modified in the NEW file context as presented in the unified diff headers (`@@ -... +... @@`).
- Do not estimate or guess line numbers outside the immediate range of the explicit diff blocks. If you reference a line that is not modified or contextualized directly within the diff hunk, GitHub will reject the payload with a 422 validation failure.
"""


def main():
    metadata = get_pr_metadata()
    diff_data = get_pr_diff()

    # Bundle description intent with the code changes
    prompt_content = f"""
=== PULL REQUEST METADATA ===
Title: {metadata["title"]}
Description:
{metadata["body"]}

=== UNIFIED CODE DIFF ===
{diff_data}
"""

    print(prompt_content)

    client = genai.Client(api_key=GEMINI_API_KEY)

    response = client.models.generate_content(
        model=MODEL_NAME,
        contents=prompt_content,
        config=types.GenerateContentConfig(
            system_instruction=SYSTEM_INSTRUCTION,
            response_mime_type="application/json",
            response_schema=ReviewPayload,
            temperature=0.1,  # Low temperature minimizes creative hallucination of lines
        ),
    )

    try:
        review_data = json.loads(response.text)
        post_review_comments(review_data.get("comments", []))
    except Exception as e:
        print(f"Failed to parse model output or post review: {e}")
        print(f"Raw response: {response.text}")
        sys.exit(1)


if __name__ == "__main__":
    main()
